# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-20.04
    container: lironavon/docker-puppeteer-container:14.16.0
    env:
      CI: true
    steps:
      # add git to the container and set it up with the token
      - name: setup git in container
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # cache the dependencies from any node_modules directory
      - name: cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          
        # install the dependencies
      - name: install dependencies
        run: |
              cd ./client 
              npm install
              npm ci --ignore-scripts    
              
      # install the dependencies
      - name: install dependencies
        run: npm ci --ignore-scripts

      # run the tests
      - name: test
        run: npm test
